SewaPatra/Models/Area.cs
using System.ComponentModel.DataAnnotations;

namespace SewaPatra.Models
{
    public class Area
    {
        [Key]
        [Required]
        public int Id { get; set; }
        [Required]
        public string Area_name { get; set; }
        [Required]
        public string Area_type { get; set; }
	    public string? Under { get; set; }

    }
}

SewaPatra/Models/Coordinator.cs
namespace SewaPatra.Models
{
    public class Coordinator
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Mobile_No { get; set; }
        public string Alternate_Mobile_No { get; set; }

        public string Email { get; set; }
        public int Area_Under { get; set; }
        public string? location { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedAt { get; set; }
        public string? AreaName { get; set; }
    }
}

SewaPatra/Models/DonationBox.cs
namespace SewaPatra.Models
{
    public class DonationBox
    {
        public int Id { get; set; }
        public string Box_Number { get; set; }        
        public bool Active { get; set; }
    }
}

SewaPatra/Models/Donor.cs
namespace SewaPatra.Models
{
    public class Donor
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Mobile_No { get; set; }
        public string Mobile_no2 { get; set; }
        public string Email { get; set; }
        public int Area { get; set; }
        public int Coordinator { get; set; }
        public string? Location { get; set; }
        public bool Active { get; set; }
        public string? AreaName { get; set; }
        public string? CoordinatorName { get; set; }

    }
}

SewaPatra/Controllers/MasterController.cs
using Microsoft.AspNetCore.Mvc;
using SewaPatra.BusinessLayer;
using SewaPatra.DataAccess;
using SewaPatra.Helpers;
using SewaPatra.Models;

namespace SewaPatra.Controllers
{
    public class MasterController : Controller
    {
        private readonly AreaService _AreaService;
        private readonly CoordinatorService _CoordinatorService;
        private readonly DonationBoxService _DonationBoxService;
        private readonly DonorService _DonorService;
        private readonly DropDownService _dropDownService;

        public MasterController(AreaService areaService,CoordinatorService coordinatorService,DonationBoxService donationBoxService,
            DonorService donorService,DropDownService dropDownService)
        {
            _AreaService = areaService;
            _CoordinatorService = coordinatorService;
            _DonationBoxService = donationBoxService;
            _DonorService = donorService;
            _dropDownService = dropDownService;
        }
        #region Area
        public IActionResult AreaList() 
        {
            List<Area> areas = _AreaService.GetAllAreas();
            return View(areas);
        }
        public IActionResult Area()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Area(Area area)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isInserted = _AreaService.InsertArea(area);
                    if (isInserted)
                    {
                        TempData["Message"] = "Area Added Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Failed to Add Area";
                    }
                }
                else
                {
                    TempData["Message"] = "Invalid data";
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message.ToString();
                return RedirectToAction("Area");
            }            
            return RedirectToAction("Area");
        }
        public IActionResult EditArea(int id)
        {
            var area = _AreaService.GetAreaById(id);
            if (area == null)
            {
                return NotFound();
            }
            return View(area);
        }
        public IActionResult DeleteArea(int id)
        {
            try 
            {
                bool isDeleted = _AreaService.DeleteArea(id);
                TempData["Message"] = "Area Deleted Successfully";
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message.ToString();
                return RedirectToAction("AreaList");
            }
            
            return RedirectToAction("AreaList");
        }
        [HttpPost]
        public IActionResult EditArea(Area model)
        {
            if (ModelState.IsValid)
            {
                bool isUpdated = _AreaService.UpdateArea(model);
                if (isUpdated)
                {
                    TempData["Message"] = "Area updated successfully!";
                    return RedirectToAction("AreaList");
                }
                TempData["Message"] = "Update failed!";
            }
            return RedirectToAction("Area");
        }
        #endregion
        #region Coordinator
        public IActionResult CoordinatorList()
        {
            ViewBag.Message = TempData["Message"];
            List<Coordinator> coordinators = _CoordinatorService.GetAllCoordinator();
            return View(coordinators);
        }      
      
        public IActionResult Coordinator()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.Areas = _dropDownService.GetAreaList();
            return View();
        }
        [HttpPost]
        public IActionResult Coordinator(Coordinator coordinator)
        {
            if (ModelState.IsValid)
            {
                bool isInserted = _CoordinatorService.InsertCoordinator(coordinator);
                if (isInserted)
                {
                    TempData["Message"] = "Coordinator Added Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Add Coordinator";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return RedirectToAction("Coordinator");
        }
        public IActionResult EditCoordinator(int id)
        {
            var coordinator = _CoordinatorService.GetCoordinatorById(id);
            ViewBag.Areas = _dropDownService.GetAreaList();
            if (coordinator == null)
            {
                return NotFound();
            }
            return View(coordinator);
        }
        public IActionResult DeleteCoordinator(int id)
        {
            bool isDeleted = _CoordinatorService.DeleteCoordinator(id);
            if (isDeleted)
            {
                TempData["Message"] = "Coordinator Deleted Successfully!";
                return RedirectToAction("CoordinatorList");
            }
            return RedirectToAction("CoordinatorList");
        }
        [HttpPost]
        public IActionResult EditCoordinator(Coordinator model)
        {
            if (ModelState.IsValid)
            {
                bool isUpdated = _CoordinatorService.UpdateCoordintor(model);
                if (isUpdated)
                {
                    TempData["Message"] = "Coordinator Updated Successfully!";
                    return RedirectToAction("CoordinatorList");
                }
                TempData["Message"] = "Update failed!";
            }
            return RedirectToAction("Coordinator");
        }
        #endregion
        #region DonationBox
        public IActionResult DonationBoxList()
        {
            List<DonationBox> donationBoxes = _DonationBoxService.GetAllDonationBox();
            return View(donationBoxes);
        }
        public IActionResult DonationBox()
        {
            return View();
        }
        [HttpPost]
        public IActionResult DonationBox(DonationBox donationBoxes)
        {
            if (ModelState.IsValid)
            {
                bool isInserted = _DonationBoxService.InsertDonationBox(donationBoxes);
                if (isInserted)
                {
                    TempData["Message"] = "DonationBox Added Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Add DonationBox";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return RedirectToAction("DonationBox");
        }
        public IActionResult EditDonationBox(int id)
        {
            var coordinator = _DonationBoxService.GetDonationBoxById(id);
            if (coordinator == null)
            {
                return NotFound();
            }
            return View(coordinator);
        }
        public IActionResult DeleteDonationBox(int id)
        {
            bool isDeleted = _DonationBoxService.DeleteDonationBox(id);
            return RedirectToAction("CoordinatorList");
        }
        [HttpPost]
        public IActionResult EditDonationBox(DonationBox model)
        {
            if (ModelState.IsValid)
            {
                bool isUpdated = _DonationBoxService.UpdateDonationBox(model);
                if (isUpdated)
                {
                    return RedirectToAction("DonationBoxList");
                }
                TempData["Message"] = "Update failed!";
            }
            return RedirectToAction("DonationBox");
        }
        #endregion
        #region Donor
        public IActionResult DonorList()
        {
            ViewBag.Message = TempData["Message"];
            List<Donor> donor = _DonorService.GetAllDonor();
            return View(donor);
        }
        public IActionResult Donor()
        {            
            ViewBag.Areas = _dropDownService.GetAreaList();
            ViewBag.Coordinators = _dropDownService.GetCoordinatorList();
            ViewBag.Message = TempData["Message"];
            return View();
        }
        [HttpPost]
        public IActionResult Donor(Donor donor)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isInserted = _DonorService.InsertDonor(donor);
                    if (isInserted)
                    {
                        TempData["Message"] = "Donor Added Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Failed to Add Donor";
                    }
                }
                else
                {
                    TempData["Message"] = "Invalid data";
                }
            }
            catch (Exception ex)
            {
                TempData["Message"] = ex.Message.ToString();
                return RedirectToAction("Donor");
            }            
            return RedirectToAction("Donor");
        }
        public IActionResult EditDonor(int id)
        {
            var donor = _DonorService.GetDonorById(id);
            ViewBag.Areas = _dropDownService.GetAreaList();
            ViewBag.Coordinators = _dropDownService.GetCoordinatorList();
            if (donor == null)
            {
                return NotFound();
            }
            return View(donor);
        }
        public IActionResult DeleteDonor(int id)
        {
            bool isDeleted = _DonorService.DeleteDonor(id);
            if (isDeleted)
            {
                TempData["Message"] = "Donor Deleted Successfully!";
                return RedirectToAction("DonorList");
            }

SewaPatra/Views/Master/Area.cshtml
@model SewaPatra.Models.Area

@{
    ViewBag.Title = "Add Area";
}

@if (TempData["Message"] != null)
{
    <div class="alert alert-success" role="alert">
        @TempData["Message"]
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Add Area</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item">Area</li>
                <li class="breadcrumb-item active">Add Area</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Form -->
    <form class="row g-3" method="post" asp-action="Area" asp-controller="Master">
        <div class="col-3">
            <label asp-for="Area_name" class="form-label">Area Name</label>
            <input type="text" class="form-control" asp-for="Area_name" id="areaName" required>
        </div>
        <div class="col-3">
            <label asp-for="Area_type" class="form-label">Area Type</label>
            <input type="text" class="form-control" asp-for="Area_type" id="areaType" required>
        </div>
       @*  <div class="row mb-3">
            <label asp-for="Under" class="form-label">Under</label>
            <div class="col-3">
                <select asp-for="Under" class="form-select" aria-label="Select Coordinator">
                    <option selected>select Coordinator</option>
                    <option value="1">Ram</option>
                    <option value="2">Shyam</option>
                </select>
            </div>
        </div> *@
        <div class="text-Left">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="~/Master/AreaList" class="btn btn-primary">Cancel</a>
        </div>
    </form>

</div>

SewaPatra/Views/Master/AreaList.cshtml
@model List<SewaPatra.Models.Area>

@{
    ViewData["Title"] = "Area List";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<style>
    #tempMessage {
        position: fixed; /* Fixed positioning to overlay content */
        top: 50px; /* Adjust as needed */
        left: 50%;
        transform: translateX(-50%); /* Center horizontally */
        z-index: 1000; /* Ensure it's on top of other elements */
        /*display: none; /* Initially hidden */
    }
</style>
@if (TempData["Message"] != null)
{
    <div id="tempMessage" class="alert alert-info">
        @TempData["Message"]
    </div>
}
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="pagetitle mt-2">
                        <h1>Area List</h1>
                        <nav>
                            <ol class="breadcrumb">
                                @* <li class="breadcrumb-item"><a href="index.html">Home</a></li> *@
                                <li class="breadcrumb-item">Master</li>
                                <li class="breadcrumb-item active">Area List</li>
                            </ol>
                        </nav>
                    </div>
                    <div style="display:flex;justify-content:flex-end;">
                        <a asp-controller="Master" asp-action="Area" style="margin-right: 13.6%;font-size: 12px; padding: 2px 8px;" class="btn btn-warning btn-sm">Add New</a>
                    </div>
                    <div class="table-responsive table-striped">
                        <table id="DataTable" class="table align-middle display nowrap datatable" style="width:100%">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Area Name</th>
                                    <th>Area Type</th>
                                    @* <th>Under</th> *@
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count > 0)
                                {
                                    int sno = 1;
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@sno</td>
                                            <td>@item.Area_name</td>
                                            <td>@item.Area_type</td>
                                            @* <td>@item.Under</td> *@
                                            <td>
                                                <a asp-controller="Master" asp-action="EditArea" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Edit</a>
                                                <a asp-controller="Master" asp-action="DeleteArea" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Delete</a>
                                            </td>
                                        </tr>
                                        sno++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>
                    <!-- Table with stripped rows -->
                   @*  <table class="table datatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Area Name</th>
                                <th>Area Type</th>
                                <th>Under</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if(Model != null && Model.Count > 0)
                            {
                                int sno = 1;
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@sno</td>
                                        <td>@item.Area_name</td>
                                        <td>@item.Area_type</td>
                                        <td>@item.Under</td>
                                        <td>
                                            <a asp-controller="Master" asp-action="EditArea" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Edit</a>
                                            <a asp-controller="Master" asp-action="DeleteArea" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Delete</a>
                                        </td>
                                    </tr>
                                    sno++;
                                }
                            }                            
                        </tbody>
                    </table> *@
                    <!-- End Table with stripped rows -->

                </div>
            </div>

        </div>
    </div>
</section>

SewaPatra/Views/Master/Coordinator.cshtml
@model SewaPatra.Models.Coordinator;

@{
    ViewBag.Title = "Add Coordinator";
}
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Add Coordinator</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item">Coordinator</li>
                <li class="breadcrumb-item active">Add Coordinator</li>
            </ol>
        </nav>
    </div>
    <form class="row g-3" method="post" asp-action="Coordinator" asp-controller="Master">
        <!-- Name -->
        <div class="col-md-12">
            <label for="Name" class="form-label">Name</label>
            <input type="text" class="form-control" asp-for="Name" name="Name" required>
        </div>

        <!-- Email -->
        <div class="col-md-6">
            <label for="Email" class="form-label">Email</label>
            <input type="email" class="form-control" asp-for="Email" name="Email">
        </div>

        <!-- Mobile No -->
        <div class="col-md-6">
            <label for="Mobile_No" class="form-label">Mobile No</label>
            <input type="text" class="form-control" asp-for="Mobile_No" name="Mobile_No">
        </div>

        <!-- Address -->
        <div class="col-12">
            <label for="Address" class="form-label">Address</label>
            <input type="text" class="form-control" asp-for="Address" name="Address" placeholder="University Road, Kalimati">
        </div>

        <!-- Alternate Mobile No -->
        <div class="col-md-6">
            <label for="Alternate_Mobile_No" class="form-label">Alternate Mobile No</label>
            <input type="text" class="form-control" asp-for="Alternate_Mobile_No" name="Alternate_Mobile_No">
        </div>

        <!-- City -->
        <div class="col-md-6">
            <label asp-for="City" class="form-label">City</label>
            <input type="text" class="form-control" asp-for="City" name="City">
        </div>

        <!-- Area Under -->
        <div class="col-md-4">
            <label asp-for="Area_Under" class="form-label">Area</label>
            <select asp-for="Area_Under" asp-items="@ViewBag.Areas" class="form-select"></select>
            <span asp-validation-for="Area_Under" class="text-danger"></span>
        </div>


        <!-- Location -->
       @*  <div class="col-md-4">
            <label for="Location" class="form-label">Location</label>
            <input type="text" class="form-control" asp-for="Location" name="Location">
        </div> *@

        <!-- Status -->
        <div class="col-md-4">
            <label for="Status" class="form-label">Status</label>
            <select class="form-select" asp-for="Active" name="Active" aria-label="Select Status">
                <option selected>Choose Status</option>
                <option value="true">Active</option>
                <option value="false">Inactive</option>
            </select>
        </div>

        <!-- CreatedAt -->
        <input type="hidden" asp-for="CreatedAt" name="CreatedAt" value="@DateTime.Now" />

        <!-- Submit and Reset Buttons -->
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a href="~/Master/CoordinatorList" class="btn btn-primary">Cancel</a>
        </div>
    </form>
</div>

SewaPatra/Views/Master/CoordinatorList.cshtml
@model List<SewaPatra.Models.Coordinator>

@{
    ViewData["Title"] = "Coordinator List";
}
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="pagetitle mt-2">
                        <h1>Coordinator List</h1>
                        <nav>
                            <ol class="breadcrumb">
                                @* <li class="breadcrumb-item"><a href="index.html">Home</a></li> *@
                                <li class="breadcrumb-item">Master</li>
                                <li class="breadcrumb-item active">Coordinator List</li>
                            </ol>
                        </nav>
                    </div>
                    <div style="display:flex;justify-content:flex-end;">
                        <a asp-controller="Master" asp-action="Coordinator" style="margin-right: 13.6%;font-size: 12px; padding: 2px 8px;" class="btn btn-warning btn-sm">Add New</a>
                    </div>
                    <div class="table-responsive table-striped">
                        <table class="table datatable">
                            <thead>
                                <tr>
                                    <th>SN</th>
                                    <th>Name</th>
                                    <th>Address</th>
                                    <th>City</th>
                                    <th>Mobile No</th>
                                    <th>Alt Mobile No</th>
                                    <th>Email</th>
                                    <th>Area</th>
                                 @*    <th>Location</th> *@
                                    <th>Status</th>@* 
                                    <th>Action</th> *@
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model != null && Model.Count > 0)
                                {
                                    int sno = 1;
                                    @foreach (var item in Model)
                                    {
                                        <tr>
                                            <td>@sno</td>
                                            <td>@item.Name</td>
                                            <td>@item.Address</td>
                                            <td>@item.City</td>
                                            <td>@item.Mobile_No</td>
                                            <td>@item.Alternate_Mobile_No</td>
                                            <td>@item.Email</td>
                                            <td>@item.AreaName</td>
                                         @*    <td>@item.location</td> *@
                                            @* <td>@item.Active</td> *@
                                            <td>
                                                <a asp-controller="Master" asp-action="EditCoordinator" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Edit</a>
                                                <a asp-controller="Master" asp-action="DeleteCoordinator" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Delete</a>
                                            </td>
                                        </tr>
                                        sno++;
                                    }
                                }
                            </tbody>
                        </table>
                    </div>                    
                </div>
            </div>
        </div>
    </div>
</section>

SewaPatra/Views/Master/DonationBox.cshtml
@model SewaPatra.Models.DonationBox

@{
    ViewBag.Title = "Add Donation Box";
}
@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Add DonationBox</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Master</li>
                <li class="breadcrumb-item">Donation Box</li>
                <li class="breadcrumb-item active">Add Donation Box</li>
            </ol>
        </nav>
    </div>
    <form class="row g-3" method="post" asp-action="DonationBox" asp-controller="Master">
        <div class="col-md-6">
            <label for="Box_Number" class="form-label">Box_Number</label>
            <input type="text" class="form-control" id="Box_Number" Asp-for="Box_Number">
        </div>
        <div class="col-md-4">
            <label for="Status" class="form-label">Status</label>
            <select class="form-select" id="Status" asp-for="Active" aria-label="Select Status">
                <option selected>Choose Status</option>
                <option value="true">Active</option>
                <option value="false">Inactive</option>
            </select>
        </div>
        <div class="text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

SewaPatra/Views/Master/DonationBoxList.cshtml
@model List<SewaPatra.Models.DonationBox>

@{
    ViewData["Title"] = "Donation Box List";
}

<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="pagetitle mt-2">
                        <h1>Donation Box List</h1>
                        <nav>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">Master</li>
                                <li class="breadcrumb-item active">Donation Box List</li>
                            </ol>
                        </nav>
                    </div>
                    <div style="display:flex;justify-content:flex-end;">
                        <a asp-controller="Master" asp-action="DonationBox" style="margin-right: 13.6%;font-size: 12px; padding: 2px 8px;" class="btn btn-warning btn-sm">Add New</a>
                    </div>
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>SN</th>
                                <th>Box Number</th>
                                <th>Status</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count > 0)
                            {
                                int sno = 1;
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@sno</td>
                                        <td>@item.Box_Number</td>
                                        <td>@item.Active</td>
                                        <td>
                                            <a asp-controller="Master" asp-action="EditDonationBox" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Edit</a>
                                            <a asp-controller="Master" asp-action="DeleteDonationBox" asp-route-id="@item.Id" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Delete</a>
                                        </td>
                                    </tr>
                                    sno++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</section>