SewaPatra/Models/PaymentVoucher.cs
namespace SewaPatra.Models
{
    public class PaymentVoucher
    {
        public string P_TranId { get; set; }
        public DateTime Date { get; set; }
        public string Ledger_Name { get; set; }
        public int Coordinator { get; set; }
        public string Amount { get; set; }
        public string Remarks { get; set; }
    }
}

SewaPatra/Models/ReceiptVoucher.cs
using System.ComponentModel.DataAnnotations;

namespace SewaPatra.Models
{
    public class ReceiptVoucher
    {
        [Key]
        [Required]
        public string R_TranId { get; set; }
        public DateTime Date { get; set; }
        [Required]
        public int Sewapatra_No { get; set; }
        [Required]
        public int Donor { get; set; }
        [Required]
        public int Coordinator { get; set; }
        public string Amount { get; set; }
        public string Next_DueDate { get; set; }
        public string Remarks { get; set; }
    }
}

SewaPatra/Models/SewaPatraIssue.cs
using System.ComponentModel.DataAnnotations;

namespace SewaPatra.Models
{
    public class SewaPatraIssue
    {
        [Key]
        public string TranId { get; set; }
        [Required]
        public DateTime Entered_Date { get; set; }
        [Required]
        public int Donor { get; set; }
        [Required]
        public int Coordinator { get; set; }
        [Required]
        public int DonationBox { get; set; }
        [Required]
        public DateTime Issue_Date { get; set; }
        public string? Recurring { get; set; }
        public DateTime? Due_Date { get; set; }
        public string? Remarks { get; set; }
        public string? DonorName { get; set; }
        public string? Coordinatorname { get; set; }
        public string? DonationBoxName { get; set; }

    }
}

SewaPatra/Models/SewaPatraReceipt.cs
using System.ComponentModel.DataAnnotations;

namespace SewaPatra.Models
{
    public class SewaPatraReceipt
    {
        [Key]
        public string SPR_TranId { get; set; }
        [Required]
        public DateTime Date { get; set; }
        [Required]
        public int Donor { get; set; }
        [Required]
        public int Coordinator { get; set; }
        [Required]
        public int DonationBox { get; set; }
        [Required]
        public DateTime Receive_Date { get; set; }
        public string? Remarks { get; set; }
    }
}

SewaPatra/Controllers/EntryController.cs
using Microsoft.AspNetCore.Mvc;
using SewaPatra.BusinessLayer;
using SewaPatra.Helpers;
using SewaPatra.Models;

namespace SewaPatra.Controllers
{
    public class EntryController : Controller
    {
        private readonly SewaPatraIssueService _sewaPatraIssueService;
        private readonly PaymentVoucherService _paymentVoucherService;
        private readonly ReceiptVoucherService _receiptVoucherService;
        private readonly SewaPatraReceiptService _sewaPatraReceiptService;
        private readonly DropDownService _dropDownService;

        public EntryController(SewaPatraIssueService sewaPatraIssueService, PaymentVoucherService paymentVoucherService,
            ReceiptVoucherService receiptVoucherService, DropDownService dropDownService, SewaPatraReceiptService sewaPatraReceiptService)
        {
            _sewaPatraIssueService = sewaPatraIssueService;
            _paymentVoucherService = paymentVoucherService;
            _receiptVoucherService = receiptVoucherService;
            _dropDownService = dropDownService;
            _sewaPatraReceiptService = sewaPatraReceiptService;
        }
        #region SewaPatra Issue
        public IActionResult SewaPatraIssue()
        {
            ViewBag.DonationBoxes = _dropDownService.GetDonationBoxList();
            ViewBag.Coordinators = _dropDownService.GetCoordinatorList();
            ViewBag.Donors = _dropDownService.GetDonorList();
            ViewBag.Message = TempData["Message"];
            return View();
        }
        public IActionResult SewaPatraIssueList()
        {
            List<SewaPatraIssue> sewaPatraIssue = _sewaPatraIssueService.GetAllSewaPatraIssue();
            ViewBag.Message = TempData["Message"];
            return View(sewaPatraIssue);
        }
        [HttpPost]
        public IActionResult SewaPatraIssue(SewaPatraIssue sewaPatraIssue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isInserted = _sewaPatraIssueService.InsertSewaPatraIssue(sewaPatraIssue);
                    if (isInserted)
                    {
                        TempData["Message"] = "SewaPatra Issue Added Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Failed to Add SewaPatra Issue";
                    }
                }
                else
                {
                    TempData["Message"] = "Invalid data";
                }
            }
            catch (Exception Ex)
            {
                TempData["Message"] = Ex.Message.ToString();
            }
            return RedirectToAction("SewaPatraIssue");
        }
        public IActionResult EditSewaPatraIssue(string id)
        {
            var sewaPatraIssue = _sewaPatraIssueService.GetSewaPatraIssueById(id);
            ViewBag.DonationBoxes = _dropDownService.GetDonationBoxList();
            ViewBag.Coordinators = _dropDownService.GetCoordinatorList();
            ViewBag.Donors = _dropDownService.GetDonorList();
            if (sewaPatraIssue == null)
            {
                return NotFound();
            }
            return View(sewaPatraIssue);
        }
        [HttpPost]
        public IActionResult EditSewaPatraIssue(SewaPatraIssue sewaPatraIssue)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool isUpdated = _sewaPatraIssueService.UpdateSewaPatraIssue(sewaPatraIssue);
                    if (isUpdated)
                    {
                        TempData["Message"] = "SewaPatra Issue Updated Successfully";
                    }
                    else
                    {
                        TempData["Message"] = "Failed to Update SewaPatra Issue";
                    }
                }
                else
                {
                    TempData["Message"] = "Invalid data";
                }
            }
            catch (Exception Ex)
            {
                TempData["Message"] = Ex.Message.ToString();
            }            
            return RedirectToAction("SewaPatraIssueList");
        }
        public IActionResult DeleteSewaPatraIssue(string id)
        {
            try 
            {
                bool isDeleted = _sewaPatraIssueService.DeleteSewaPatraIssue(id);
                if (isDeleted)
                {
                    TempData["Message"] = "SewaPatra Issue Deleted Successfully!";
                }
                else 
                {
                    TempData["Message"] = "Failed To Delete SewaPatra Issue!";
                }
            }      
            catch(Exception Ex)
            {
                TempData["Message"] = Ex.Message.ToString();
            }
            return RedirectToAction("SewaPatraIssueList");
        }
        #endregion
        #region Receipt Voucher
        public IActionResult ReceiptVoucher()
        {
            ViewBag.Message = TempData["Message"];
            return View();
        }
        [HttpPost]
        public IActionResult ReceiptVoucher(ReceiptVoucher receiptVoucher)
        {
            if (ModelState.IsValid)
            {
                bool isUpdated = _receiptVoucherService.InsertReceiptVoucher(receiptVoucher);
                if (isUpdated)
                {
                    TempData["Message"] = "Receipt Voucher Inserted Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Insert Receipt Voucher";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return View();
        }
        public IActionResult ReceiptVoucherList()
        {
            ViewBag.Message = TempData["Message"];
            List<ReceiptVoucher> receiptVoucher = _receiptVoucherService.GetAllReceiptVoucher();
            return View(receiptVoucher);
        }
        #endregion
        #region Payment Voucher
        public IActionResult PaymentVoucher()
        {
            ViewBag.Message = TempData["Message"];
            return View();
        }
        public IActionResult PaymentVoucherList()
        {
            ViewBag.Message = TempData["Message"];
            List<PaymentVoucher> paymentVoucher = _paymentVoucherService.GetAllPaymentVoucher();
            return View(paymentVoucher);
        }
        [HttpPost]

        public IActionResult PaymentVoucher(PaymentVoucher paymentVoucher)
        {
            if (ModelState.IsValid)
            {
                bool isInserted = _paymentVoucherService.InsertPaymentVoucher(paymentVoucher);
                if (isInserted)
                {
                    TempData["Message"] = "Payment Voucher Added Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Add Payment Voucher Issue";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return View();
        }
        public IActionResult EditPaymentVoucher(string id)
        {
            var paymentVoucher = _paymentVoucherService.GetAllPaymentVoucherById(id);
            if (paymentVoucher == null)
            {
                return NotFound();
            }
            return View(paymentVoucher);
        }
        [HttpPost]
        public IActionResult EditPaymentVoucher(PaymentVoucher paymentVoucher)
        {
            if (ModelState.IsValid)
            {
                bool isUpdated = _paymentVoucherService.UpdatePaymentVoucher(paymentVoucher);
                if (isUpdated)
                {
                    TempData["Message"] = "Payment Voucher Updated Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Update Payment Voucher";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return View();
        }
        public IActionResult DeletePaymentVoucher(string id)
        {
            bool isDeleted = _paymentVoucherService.DeletePaymentVoucher(id);
            return RedirectToAction("PaymentVoucherList");
        }
        #endregion
        #region SewaPatra Receipt
        public IActionResult SewaPatraReceipt()
        {
            ViewBag.Message = TempData["Message"];
            ViewBag.DonationBoxes = _dropDownService.GetDonationBoxList();
            ViewBag.Coordinators = _dropDownService.GetCoordinatorList();
            ViewBag.Donors = _dropDownService.GetDonorList();
            return View();
        }
        public IActionResult SewaPatraReceiptList()
        {
            ViewBag.Message = TempData["Message"];
            List<SewaPatraReceipt> sewaPatraReceipt = _sewaPatraReceiptService.GetAllSewaPatraReceipt();
            return View(sewaPatraReceipt);
        }
        [HttpPost]
        public IActionResult SewaPatraReceipt(SewaPatraReceipt sewaPatraReceipt)
        {
            if (ModelState.IsValid)
            {
                bool isInserted = _sewaPatraReceiptService.InsertSewaPatraReceipt(sewaPatraReceipt);
                if (isInserted)
                {
                    TempData["Message"] = "SewaPatra Receipt Added Successfully";
                }
                else
                {
                    TempData["Message"] = "Failed to Add SewaPatra Receipt";
                }
            }
            else
            {
                TempData["Message"] = "Invalid data";
            }
            return View();
        }
        public IActionResult EditSewaPatraReceipt(string id)
        {
            var sewaPatraReceipt = _sewaPatraReceiptService.GetSewaPatraReceiptById(id);
            if (sewaPatraReceipt == null)
            {
                return NotFound();
            }

SewaPatra/Views/Entry/EditPaymentVoucher.cshtml
@model SewaPatra.Models.PaymentVoucher;

@{
    ViewBag.Title = "Edit Payment Voucher";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Payment Voucher</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Entry</li>
                <li class="breadcrumb-item">Edit Payment Voucher</li>
            </ol>
        </nav>
    </div>
    <form method="post" asp-action="PaymentVoucher" asp-controller="Entry">
        <div class="row mb-2">
            <label asp-for="P_TranId" style="font-size: 13px;" class="col-sm-2 col-form-label">Transaction Id</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="P_TranId" id="TranId">
            </div>
            <label asp-for="Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Date" id="enteredDate">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Ledger_Name" style="font-size: 13px;" class="col-sm-2 col-form-label">Ledger_Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Ledger_Name" id="remarks">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Amount" style="font-size: 13px;" class="col-sm-2 col-form-label">Amount</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Amount" id="Amount">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Coordinator" style="font-size: 13px;" class="col-sm-2 col-form-label">Coordinator</label>
            <div class="col-sm-4">
                <select asp-for="Coordinator" style="font-size: 10px;" class="form-select" aria-label="Select Coordinator">
                    <option selected>Select Coordinator</option>
                    <option value="1">Test1</option>
                    <option value="2">Test2</option>
                </select>
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Remarks" style="font-size: 13px;" class="col-sm-2 col-form-label">Remarks</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Remarks" id="remarks">
            </div>
        </div>
        <div class="text-Left">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

SewaPatra/Views/Entry/EditSewaPatraIssue.cshtml
@model SewaPatra.Models.SewaPatraIssue;

@{
    ViewBag.Title = "Edit SewaPatra Issue";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Sewa Patra Issue</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Entry</li>
                <li class="breadcrumb-item">Edit SewaPatra Issue</li>
            </ol>
        </nav>
    </div>
    <form method="post" asp-action="EditSewaPatraIssue" asp-controller="Entry">
        <div class="row mb-2">
            <label asp-for="TranId" style="font-size: 13px;" class="col-sm-2 col-form-label">Transaction Id</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="TranId" id="TranId">
            </div>
            <label asp-for="Entered_Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Entered_Date" id="enteredDate">
            </div>
        </div>
        @* <div class="row mb-2">

        </div> *@
        <div class="row mb-2">
            <label asp-for="Donor" style="font-size: 13px;" class="col-sm-2 col-form-label">Donor</label>
            <div class="col-sm-4">
                <select asp-for="Donor" asp-items="@ViewBag.Donors" style="font-size: 10px;" class="form-select" aria-label="Select Donor"></select>
            </div>
            <label asp-for="Coordinator" style="font-size: 13px;" class="col-sm-2 col-form-label">Coordinator</label>
            <div class="col-sm-4">
                <select asp-for="Coordinator" asp-items="@ViewBag.Coordinators" style="font-size: 10px;" class="form-select" aria-label="Select Coordinator"></select>
            </div>
        </div>
        @* <div class="row mb-2">

        </div> *@
        <div class="row mb-2">
            <label asp-for="DonationBox" style="font-size: 13px;" class="col-sm-2 col-form-label">Donation Box</label>
            <div class="col-sm-4">
                <select asp-for="DonationBox" asp-items="@ViewBag.DonationBoxes" style="font-size: 10px;" class="form-select" aria-label="Select DonationBox"></select>
            </div>
            <label asp-for="Issue_Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Issue Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Issue_Date" id="issueDate">
            </div>
        </div>
        @* <div class="row mb-2">

        </div> *@
        <div class="row mb-2">
            <label asp-for="Recurring" style="font-size: 13px;" class="col-sm-2 col-form-label">Recurring</label>
            <div class="col-sm-4">
                <select asp-for="Recurring" style="font-size: 10px;" class="form-select" aria-label="Select Recurring Date">
                    <option selected>Select Recurring Type</option>
                    <option value="yearly">Yearly</option>
                    <option value="halfYearly">Half Yearly</option>
                    <option value="quarterly">Quaterly</option>
                </select>
            </div>
            <label asp-for="Due_Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Due Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Due_Date" id="dueDate">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Remarks" style="font-size: 13px;" class="col-sm-2 col-form-label">Remarks</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Remarks" id="remarks">
            </div>
        </div>
        <div class="text-Left">
            <button type="submit" class="btn btn-primary">Save</button>
            <a href="~/Entry/SewaPatraIssueList" class="btn btn-primary">Cancel</a>
        </div>
    </form>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        const issueDateInput = document.getElementById('issueDate');
        const recurringTypeSelect = document.getElementById('recurringType');
        const dueDateInput = document.getElementById('dueDate');

        function calculateDueDate() {
            const issueDateValue = issueDateInput.value;
            const recurringTypeValue = recurringTypeSelect.value;

            if (!issueDateValue || !recurringTypeValue) {
                return; // Don't calculate if either input is empty
            }

            const issueDate = new Date(issueDateValue);
            let dueDate;

            switch (recurringTypeValue) {
                case 'yearly':
                    dueDate = new Date(issueDate.getFullYear() + 1, issueDate.getMonth(), issueDate.getDate());
                    break;
                case 'halfYearly':
                    dueDate = new Date(issueDate.getFullYear(), issueDate.getMonth() + 6, issueDate.getDate());
                    break;
                case 'quarterly':
                    dueDate = new Date(issueDate.getFullYear(), issueDate.getMonth() + 3, issueDate.getDate());
                    break;
                default:
                    return; // Do nothing if recurring type is not valid
            }

            // Format dueDate as YYYY-MM-DD for input type="date"
            const year = dueDate.getFullYear();
            const month = String(dueDate.getMonth() + 1).padStart(2, '0'); // Add 1 to get correct month
            const day = String(dueDate.getDate()).padStart(2, '0');
            dueDateInput.value = `${year}-${month}-${day}`;
        }

        // Event listeners to trigger calculation
        issueDateInput.addEventListener('change', calculateDueDate);
        recurringTypeSelect.addEventListener('change', calculateDueDate);
    });
</script>

SewaPatra/Views/Entry/EditSewaPatraReceipt.cshtml
@model SewaPatra.Models.SewaPatraReceipt;

@{
    ViewBag.Title = "SewaPatra Receipt";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>SewaPatra Receipt</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Entry</li>
                <li class="breadcrumb-item">Edit SewaPatra Receipt</li>
                @* <li class="breadcrumb-item active">Add Area</li> *@
            </ol>
        </nav>
    </div>
    <!-- Vertical Form -->
    <form method="post" asp-action="EditSewaPatraReceipt" asp-controller="Entry">
        <div class="row mb-2">
            <label asp-for="SPR_TranId" style="font-size: 13px;" class="col-sm-2 col-form-label">Transaction Id</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="SPR_TranId" id="SPR_TranId">
            </div>
            <label asp-for="Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Date" id="enteredDate">
            </div>
        </div>
        @* <div class="row mb-2">

        </div> *@
        <div class="row mb-2">
            <label asp-for="Donor" style="font-size: 13px;" class="col-sm-2 col-form-label">Donor</label>
            <div class="col-sm-4">
                <select asp-for="Donor" asp-items="@ViewBag.Donors" style="font-size: 10px;" class="form-select" aria-label="Select Donor"></select>
            </div>
            <label asp-for="Coordinator" style="font-size: 13px;" class="col-sm-2 col-form-label">Coordinator</label>
            <div class="col-sm-4">
                <select asp-for="Coordinator" asp-items="@ViewBag.Coordinators" style="font-size: 10px;" class="form-select" aria-label="Select Coordinator"></select>
            </div>
        </div>
        @* <div class="row mb-2">

        </div> *@
        <div class="row mb-2">
            <label asp-for="DonationBox" style="font-size: 13px;" class="col-sm-2 col-form-label">Donation Box</label>
            <div class="col-sm-4">
                <select asp-for="DonationBox" asp-items="@ViewBag.DonationBoxes" style="font-size: 10px;" class="form-select" aria-label="Select DonationBox"></select>
            </div>
            <label asp-for="Receive_Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Issue Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Receive_Date" id="receiveDate">
            </div>
        </div>

        <div class="row mb-2">
            <label asp-for="Remarks" style="font-size: 13px;" class="col-sm-2 col-form-label">Remarks</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Remarks" id="remarks">
            </div>
        </div>
        <div class="text-Left">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

SewaPatra/Views/Entry/PaymentVoucher.cshtml
@model SewaPatra.Models.PaymentVoucher;

@{
    ViewBag.Title = "Payment Voucher";
}

@if (ViewBag.Message != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.Message
    </div>
}
<div class="card-body">
    <div class="pagetitle mt-2">
        <h1>Payment Voucher</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">Entry</li>
                <li class="breadcrumb-item">Payment Voucher</li>
            </ol>
        </nav>
    </div>
    <!-- Vertical Form -->
    <form method="post" asp-action="PaymentVoucher" asp-controller="Entry">
        <div class="row mb-2">
            <label asp-for="P_TranId" style="font-size: 13px;" class="col-sm-2 col-form-label">Transaction Id</label>
            <div class="col-sm-4">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="P_TranId" id="TranId">
            </div>
            <label asp-for="Date" style="font-size: 13px;" class="col-sm-2 col-form-label">Date</label>
            <div class="col-sm-4">
                <input type="date" class="form-control" style="font-size: 10px;" asp-for="Date" id="enteredDate">
            </div>
        </div>       
        <div class="row mb-2">
            <label asp-for="Ledger_Name" style="font-size: 13px;" class="col-sm-2 col-form-label">Ledger_Name</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Ledger_Name" id="remarks">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Amount" style="font-size: 13px;" class="col-sm-2 col-form-label">Amount</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Amount" id="Amount">
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Coordinator" style="font-size: 13px;" class="col-sm-2 col-form-label">Coordinator</label>
            <div class="col-sm-4">
                <select asp-for="Coordinator" style="font-size: 10px;" class="form-select" aria-label="Select Coordinator">
                    <option selected>Select Coordinator</option>
                    <option value="1">Test1</option>
                    <option value="2">Test2</option>
                </select>
            </div>
        </div>
        <div class="row mb-2">
            <label asp-for="Remarks" style="font-size: 13px;" class="col-sm-2 col-form-label">Remarks</label>
            <div class="col-sm-10">
                <input type="text" class="form-control" style="font-size: 10px;" asp-for="Remarks" id="remarks">
            </div>
        </div>
        <div class="text-Left">
            <button type="submit" class="btn btn-primary">Save</button>
            <button type="reset" class="btn btn-secondary">Reset</button>
        </div>
    </form>
</div>

SewaPatra/Views/Entry/PaymentVoucherList.cshtml
@model List<SewaPatra.Models.PaymentVoucher>

@{
    ViewData["Title"] = "Payment Voucher List";
}
<section class="section">
    <div class="row">
        <div class="col-lg-12">
            <div class="card">
                <div class="card-body">
                    <div class="pagetitle mt-2">
                        <h1>Payment Voucher List</h1>
                        <nav>
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item">Entry</li>
                                <li class="breadcrumb-item active">Payment Voucher List</li>
                            </ol>
                        </nav>
                    </div>
                    <div style="display:flex;justify-content:flex-end;">
                        <a asp-controller="Entry" asp-action="PaymentVoucher" style="margin-right: 13.6%;font-size: 12px; padding: 2px 8px;" class="btn btn-warning btn-sm">Add New</a>
                    </div>
                    <table class="table datatable">
                        <thead>
                            <tr>
                                <th>Voucher Id</th>
                                <th>Date</th>
                                <th>Party Name</th>
                                <th>Coordinator</th>
                                <th>Amount</th>
                                <th>Remarks</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null && Model.Count > 0)
                            {
                                int sno = 1;
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@sno</td>
                                        <td>@item.Date</td>
                                        <td>@item.Ledger_Name</td>
                                        <td>@item.Coordinator</td>
                                        <td>@item.Amount</td>      
                                        <td>@item.Remarks</td>
                                        <td>
                                            <a asp-controller="Entry" asp-action="EditPaymentVoucher" asp-route-id="@item.P_TranId" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Edit</a>
                                            <a asp-controller="Entry" asp-action="DeletePaymentVoucher" asp-route-id="@item.P_TranId" style="background-color: #F1592A;color: #000000; font-size: 9px; padding: 2px 8px;" class="btn btn-sm">Delete</a>
                                        </td>
                                    </tr>
                                    sno++;
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>

        </div>
    </div>
</section>